instrumentation:
check:
  # For all files as an aggregate.
  global:
    statements: 85
    lines: 85
    branches: 85
    functions: 85

  # For each and every file on an individual basis.
  each:
    statements: 85
    lines: 85
    branches: 85
    functions: 85